version: "3.9"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - sample-project-db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myawesomeapp
      MYSQL_DATABASE: mydb
      MYSQL_USER: pepe
      MYSQL_PASSWORD: supersecretpassword
    
  wordpress:
    depends_on:
      - db
    build: sample-project
    volumes:
      - sample-project-config:/var/www/html
    ports:
      - "8080:8080"
volumes:
  sample-project-db-data: {}
  sample-project-config: {}