version: "3.9"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - sample-project-db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    
  wordpress:
    depends_on:
      - db
    build: sample-project
    volumes:
      - sample-project-config:/var/www/html
    ports:
      - "${PUBLIC_PORT}:8080"
volumes:
  sample-project-db-data: {}
  sample-project-config: {}
